select * from gamble.clientes
where documento=1234567890

Insert into GAMBLE.CLIENTES (DOCUMENTO,TOTALPUNTOS,USUARIO,FECHASYS,NOMBRES,APELLIDO1,APELLIDO2,FECHANACIMIENTO,TELEFONO,DIRECCION,TIPO_DEPTO,CODDEPTO,TIPO_MUNICIPIO,CODMUNICIPIO,ENT_SEXO,DAT_DTO_SEXO,DOCALTERNO,NRO_FAVORITO,
VERSION,CCOSTO,MAIL,NOMBRE1,NOMBRE2,CELULAR,ACEPTAPOLITICATDP,CLIENTEVENDEDOR,CLAVECANAL,TPOTRT_CODIGO_NACION,TRT_CODIGO_NACION,TPOTRT_CODIGO_EXPDOC,TRT_CODIGO_EXPDOC,FECHAEXPDOC,DTO_CODIGO_TPDOC,ENT_CODIGO_TPDOC,IDLOGIN,SECURITY_TOKEN) 
values ('&DOCUMENTO','u+#ajÕ','JBOSS',to_date('27/06/18','DD/MM/RR'),'DUBAN','VALENCIA','CASTANO',to_date('27/01/81','DD/MM/RR'),'&TELEFONO','','6','30','8','965','60','33','&DOCUMENTO','00000','0','0','&CORREO@GMAIL.com',null,null,null,null,null,'101010',null,null,null,null,null,null,null,null,null);

Conexion DEMO:

user = INSERTACLIENTES
password = 01e8dc3934

PORT = 172.20.1.174:1521
USER = @demopb